id = "languagetool-lsp"
name = "LanguageTool Checker"
version = "0.1.0"
schema_version = 1
authors = ["Lars Wrenger <lars@wrenger.net>"]
description = "Spelling, grammar, and style checks using LanguageTool."
repository = "https://github.com/wrenger/languagetool-lsp"

[language_servers.languagetool-lsp]
name = "LanguageTool LSP"
languages = ["Markdown", "LaTeX", "Typst", "Plaintext"]
